services:
  - type: web
    name: bot-mines-backend
    runtime: docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
